language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  local_dir: build
  overwrite: true
  on:
    branch: develop
